name: Build Docker Image

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: latest

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}
          docker build -t $IMAGE_ID .

      - name: Log into Container Registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to Container Registry
        if: ${{ !env.ACT }}
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}
          docker push $IMAGE_ID
