name: Build Docker Image
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: latest
  IMAGE_ID: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_ID }} .

      - name: Log into Container Registry
        if: ${{ secrets.GITHUB_TOKEN }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to Container Registry
        if: ${{ !env.ACT }}
        run: |
          docker push ${{ env.IMAGE_ID }}
